### ISSUE TITLE
Library fails to load (Microlibrary.js looking for package.json in strange places)

### ISSUE THREAD

**Issue by pv2b** [Native-Coder/node-bungie-lib#13]
So, I decided to take your library for a spin (it looks great for a project I'm working on).

Unfortunately, I'm stuck at the starting line even failing to require the library. The minimum code to reproduce is as follows:

```
const BungieLib = require( 'bungie-net-api' );
```

I've got this as `C:\Users\pvz\src\lala\lala.js` inside my project directory. `C:\Users\pvz\src\lala` contains my project and there's npm init and npm install bungie-net-api run inside this directory.

So this is what I run into when trying to run this very minimal code:

```
C:\Users\pvz\src\lala (user-database -> origin) (lala@1.0.0)
λ cat lala.js
const BungieLib = require( 'bungie-net-api' );

C:\Users\pvz\src\lala (user-database -> origin) (lala@1.0.0)
λ node lala.js
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\pvz\src\lala/../package.json'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at Object.<anonymous> (C:\Users\pvz\src\lala\node_modules\bungie-net-api\micro-libraries\MicroLibrary.js:12:29)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

C:\Users\pvz\src\lala (user-database -> origin) (lala@1.0.0)
λ
```

I have no idea why it's trying to look in the directory above my project directory for my package.json?

The offending LOC is here: https://github.com/Native-Coder/node-bungie-lib/blob/65d044af26c9f88d0803b02b6a58aa2982f46f38/micro-libraries/MicroLibrary.js#L10

**Comment by pv2b** [comment]
After some further investigation it seems the problem is actually here:

https://github.com/Native-Coder/node-bungie-lib/blob/65d044af26c9f88d0803b02b6a58aa2982f46f38/micro-libraries/MicroLibrary.js#L9-L12

At line 12, the library just assumes that the package.json file is inside a folder exactly one level up from the folder where the main script is running. That's not a safe assumption to make, especially not in the simple example I had where the lala.js was in the same folder as package.json.

Correct code would have to start looking for package.json at the path where the script is located, and then keep going up in the directory tree until it finds one.

I've found an NPM module that does this: https://www.npmjs.com/package/find-package-json

Since the node-bungie-lib project has the goal of not having any dependencies, we can't just npm install this into this module, but the find-package-json is an excellent candidate for just grabbing the "good stuff" and making it part of node-bungie-lib. find-package-json has no dependencies of its own, it is MIT licensed, and it fits into a single file.

I'll see if I can't submit a PR to fix this.
